services:
  frontend:
    extends:
      file: ../back/compose.yaml
      service: frontend
    container_name: frontend_frontend
    build:
      context: .
      target: dev
    volumes:
      - .:/app

  backend:
    extends:
      file: ../back/compose.yaml
      service: backend
    image: nosebook-image
    container_name: frontend_backend
    build: ""
    
  db:
    extends:
      file: ../back/compose.yaml
      service: db
    image: nosebook-postgres
    container_name: frontend_db

  db-prometheus-exporter:
    extends:
      file: ../back/compose.yaml
      service: db-prometheus-exporter
    container_name: frontend_db_exporter

  rabbitmq:
    extends:
      file: ../back/compose.yaml
      service: rabbitmq
    container_name: frontend_rabbitmq

  notification:
    extends:
      file: ../back/compose.yaml
      service: notification
    container_name: frontend_notification
    
secrets:
  db-password:
    file: db-password.txt
